name: Release

on:
  push:
    tags:
      - 'v*'

  workflow_dispatch:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

env:
  DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer

jobs:
  test_apple_platforms:
    name: Test on iOS
    runs-on: macos-latest
    strategy:
      matrix:
        destination:
          - "platform=iOS Simulator,name=iPhone 15"

    steps:
      - uses: actions/checkout@v4
      - name: Build MappIntelligenceiOS
        run: |
          set -o pipefail
          xcodebuild build --workspace MappIntelligenceSDK.workspace \
                     -destination "${{ matrix.destination }}" \
                     CODE_SIGN_IDENTITY="" \
                     CODE_SIGNING_REQUIRED=NO \
                     CODE_SIGNING_ALLOWED=NO \
                     GCC_PRECOMPILE_PREFIX_HEADER=NO \
                     clean build | xcbeautify
      - name: Create config file for build
        run: |
          mkdir -p MappIntelligenceDemoApp/MappIntelligenceDemoApp
          echo "${{ secrets.APPOXEECONFIG }}" | base64 --decode > MappIntelligenceDemoApp/MappIntelligenceDemoApp/AppoxeeConfig.plist
          echo "${{ secrets.SETUPFORLOCALTESTING }}" | base64 --decode > MappIntelligenceDemoApp/MappIntelligenceDemoApp/SetupForLocalTesting.plist
      - name: Test platform ${{ matrix.destination }}
        run: |
          set -o pipefail
          cd MappIntelligenceDemoApp
          xcodebuild --workspace MappIntelligenceSDK.workspace -scheme MappIntelligenceDemoApp \
                     -destination "${{ matrix.destination }}" \
                     CODE_SIGN_IDENTITY="" \
                     CODE_SIGNING_REQUIRED=NO \
                     CODE_SIGNING_ALLOWED=NO \
                     GCC_PRECOMPILE_PREFIX_HEADER=NO \
                     clean build | xcbeautify


  test_spm:
    name: Test SPM
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Create config file for build
      run: |
        mkdir -p MappIntelligenceDemoApp/MappIntelligenceDemoApp
        echo "${{ secrets.APPOXEECONFIG }}" | base64 --decode > MappIntelligenceDemoApp/MappIntelligenceDemoApp/AppoxeeConfig.plist
        echo "${{ secrets.SETUPFORLOCALTESTING }}" | base64 --decode > MappIntelligenceDemoApp/MappIntelligenceDemoApp/SetupForLocalTesting.plist
    - name: Build for iOS
      run: |
        xcodebuild -scheme MappIntelligenceSDK \
                   -destination "platform=iOS Simulator,name=iPhone 15" \
                   CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO \
                   clean build | xcbeautify
        xcodebuild -scheme MappIntelligenceiOS \
                   -destination "platform=iOS Simulator,name=iPhone 15" \
                   CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO \
                   clean build | xcbeautify
        cd MappIntelligenceDemoApp
        xcodebuild -scheme MappIntelligenceDemoApp \
                   -destination "platform=iOS Simulator,name=iPhone 15" \
                   CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO \
                   GCC_PRECOMPILE_PREFIX_HEADER=NO \
                   clean build | xcbeautify
      
  test_cocoapods:
    name: Test Cocoa Pods
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@master
    - name: Create config file for build
      run: |
        mkdir -p MappIntelligenceDemoApp/MappIntelligenceDemoApp
        echo "${{ secrets.APPOXEECONFIG }}" | base64 --decode > MappIntelligenceDemoApp/MappIntelligenceDemoApp/AppoxeeConfig.plist
        echo "${{ secrets.SETUPFORLOCALTESTING }}" | base64 --decode > MappIntelligenceDemoApp/MappIntelligenceDemoApp/SetupForLocalTesting.plist
    - name: Switch XCode Version
      run: sudo xcode-select -s /Applications/Xcode_15.4.app
    - name: Install Dependences
      run: |
        cd Example
        pod repo update
        pod install
      shell: bash
    - name: Test Only
      uses: ty0x2333/cocoapods-action@master
      with:
        scheme: 'exampleTests'
        additional_build_params: -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.5'
        lint: false

      

  release:
    needs: [test_apple_platforms, test_spm, test_cocoapods]
    name: Create a new GitHub release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: woke
        uses: get-woke/woke-action@v0
        with:
          fail-on-error: true
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: '5.0.13'
          release_name: Release 5.0.13
          generate_release_notes: true
          token: ${{ secrets.TOKEN_GB }}
